spring.application.name=resume-adjuster
server.port=8080


logging.level.org.springframework.security=DEBUG

# AWS s3
cloud.aws.credentials.access-key="AKIA42PHHN3BJVTPEN4P"
cloud.aws.credentials.secret-key="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"
cloud.aws.region.static=us-east-1
cloud.aws.stack.auto=false

# S3 bucket name
app.awsServices.bucketName=resume-adjuster123

# file size limitation
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB



# Database postgreSQL

spring.datasource.url=jdbc:postgresql://localhost:5432/resume_adjuster_db
spring.datasource.username=postgres
spring.datasource.password=root123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
#spring.data.redis.password=
spring.data.redis.database=0
spring.data.redis.timeout=60000

# Redis
# Redis
spring.data.redis.lettuce.pool.max-active=4
spring.data.redis.lettuce.pool.max-idle=4
spring.data.redis.lettuce.pool.min-idle=0
spring.data.redis.lettuce.pool.max-wait=100ms


# JWT scretKey
jwt.secret="F1cBXnaBxtFFvczDWk640YOLlrvNAJAxTdRGVQBFRAAbQmwoZKZLCHGvpA9xDqAx
aItwGYUtMyqqGUWpI2TcoA=="


# firebase credentials path
firebase.credentials.path=classpath:firebase-credentials.json